# Generated by Django 2.2.6 on 2020-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200309_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='https://https://nyc3.digitaloceanspaces.com/media/'),
        ),
    ]
